trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1)(92a23ff9-4506-4981-af48-d0832ba7eb21)'
    subscriptionId: '92a23ff9-4506-4981-af48-d0832ba7eb21'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'appdevops'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/SergeyTorotska/appservice/main/app1.json'
    deploymentMode: 'Incremental'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(1)(92a23ff9-4506-4981-af48-d0832ba7eb21)'
    appType: 'webAppLinux'
    WebAppName: 'myWebApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/apps/app-service-web-html-get-started-master.zip'
